export const LOAD_MEDIA_ITEMS_SUCCESS = "LOAD_MEDIA_ITEMS_SUCCESS";
export const LOAD_DIRECTORS_SUCCESS = "LOAD_DIRECTORS_SUCCESS";
export const UPDATE_MEDIA_ITEM_SUCCESS = "UPDATE_MEDIA_ITEM_SUCCESS";
export const CREATE_MEDIA_ITEM_SUCCESS = "CREATE_MEDIA_ITEM_SUCCESS";
export const UPDATE_DIRECTOR_SUCCESS = "UPDATE_DIRECTOR_SUCCESS";
export const CREATE_DIRECTOR_SUCCESS = "CREATE_DIRECTOR_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
